### ISSUE TITLE
All sections load empty details

### ISSUE THREAD

**Issue by Olamatto** [kevalpatel2106/green-build#13]
#### Expected behavior
The green build application is meant to show view and manage your continuous integration projects, each sections after logging in and enabling all repository are meant to bring forth repository details so as to enable work on the repository, such as view and editing.

#### Actual Behavior 
After logging in and clicking on the repository, all tabs in the application load empty pages.

#### How to reproduce
- Download and install the application [here](http://bit.ly/2KitKV4)
- Lunch the application 
- Select "Travis CI (For open source projects)"
- Paste your access token

####How to get access token for new users
- click on "where can i find my access token" to know how to get it
- Click on the go to profile, log in with your github account.
- Enable all repository
- Now copy your access token 
-  Go back to the app Paste your access token 
<hr>
- Click on log in
- Select a repository 

And nothing shows in the Build section, variable, cron,  and cache

<hr>

Application version: v 1.1.1
Operating system: Android v7.0

#### Recording Of The Bug
https://youtu.be/Yx4W_yVXO5I

**Comment by kevalpatel2106** [comment]
You need to set up travis.yml first and run at least one build.
