### ISSUE TITLE
Repository branches are not available

### ISSUE THREAD

**Issue by Olamatto** [kevalpatel2106/green-build#14]
#### Expected behavior
The application ought to load all repository branches, which would refelct in the add schedule new cron section

#### Actual Behavior 
While trying to add schedule new cron, the branches refuse to load, it keeps saying no branch found

#### How to reproduce
- Download and install the application [here](http://bit.ly/2KitKV4)
- Lunch the application 
- Select "Travis CI (For open source projects)"
- Paste your access token

#### How to get access token for new users
- click on "where can i find my access token" to know how to get it
- Click on the go to profile, log in with your github account.
- Enable all repository
- Now copy your access token 
-  Go back to the app Paste your access token 
<hr>

- Click on log in
- Select a repository 
- Click on Cron
- Click the add button 
- Click on select branch
- It load for a while,  then say "No branch found"

<hr>

Application version: v 1.1.1
Operating system: Android v7.0

#### Recording Of The Bug
https://youtu.be/aWQYOmCcqcE

**Comment by iykex** [comment]
if am right,  snakespeed.github.io used in here in the video it
can't be located *check picture below. 
[![Screenshot_20180526-174707.png](https://s7.postimg.cc/5u3rq5x2j/Screenshot_20180526-174707.png)](https://postimg.cc/image/9dppfyzs7/)

also, you have to create ".travis.yml" , so if u don't know how to, then read that [HERE](https://docs.travis-ci.com/).

as you can see, mine works fine.
[![Screenshot_20180526-175845.png](https://s33.postimg.cc/noanfjiun/Screenshot_20180526-175845.png)](https://postimg.cc/image/nbj99d0kr/)

**Comment by Olamatto** [comment]
But it us the same on all my repository, that is not a url,  just a repo name

**Comment by iykex** [comment]
@Olamatto show a screenshot, or your "said" repository for assistance.
or make sure u have the right configurations on travis-ci.org

**Comment by kevalpatel2106** [comment]
@Olamatto It seems like you haven't set Travis CI pipeline into your project. That's why Travis not able to pull any branches for your project and it returns empty branches list. As the branches list are not from your GitHub repo. It's the list of branches which Travis build in the past. You can see this [here](https://travis-ci.org/Olamatto/snakespeed.github.io/branches) on the Travis website.

As @iykequame suggested you need to first set up travis.yml first and run a build.
