### ISSUE TITLE
Incorrect build time

### ISSUE THREAD

**Issue by janbaudisch** [kevalpatel2106/green-build#20]
My build times are always one our ahead of what they should be. As I am also one hour ahead of UTC, there might be a wrong time conversion going on?

**Comment by kevalpatel2106** [comment]
@flyingP0tat0 Can you post a screenshot of the screen that displays build times? Also, let me know what the actual build time should be. If your project is open source, kindly send me the link of your project.

**Comment by janbaudisch** [comment]
![example](https://user-images.githubusercontent.com/17090753/42028187-df67c8d8-7acb-11e8-8c7f-7430cc888cd4.jpg)

There is an interesting thing to note here: The first one is a running build, both build duration and build time are one hour too much. But already done builds (like the second one), seem to display both correctly.

I build my projects on `travis-ci.com`, in case this is important.
