### ISSUE TITLE
Error : Invalid trigger type api.

### ISSUE THREAD

**Issue by iykex** [kevalpatel2106/green-build#3]
App not opening to content

[![Screenshot_20180429-185342.png](https://s7.postimg.cc/4j4viejkb/Screenshot_20180429-185342.png)](https://postimg.cc/image/ww0d8v5af/)

**Comment by iykex** [comment]
Screen_Record
https://drive.google.com/file/d/1n-2FX05Q2ex6YXl0BsvhUtXCRzBEJMJ2/view?usp=drivesdk

**Comment by kevalpatel2106** [comment]
@iykequame Thank you for reporting this issue. This issue occurred due to the build that was triggered by Travis API.  I resolved it in c0362587afe928f6dd611549ceac3a5c1a0a4e68. It will available in the next release.

**Comment by kevalpatel2106** [comment]
Published the fix in v1.0.1. Feel free to open the issue if the issue still persists.
